services:
  - type: web
    name: plataforma-docente
    env: node
    region: ohio
    plan: free
    nodeVersion: 20.17.0
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
